tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.
install:
  - composer install
  - composer update --no-interaction

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.clover