language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.* DEPENDENCIES=dev
    - php: hhvm-stable
      sudo: required
      dist: trusty
      group: edge
  allow_failures:
    - php: hhvm-stable

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - phpenv config-rm xdebug.ini || true
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer install
  - composer update --no-interaction

script:
  - phpunit
